// Single source of truth for the toss version.
// Reads package.json, validates the version as strict semver, and writes
// src/version.ts. The version is emitted via JSON.stringify (a serializer) — never
// string-interpolated into source — so even a crafted version string can't become
// executable code in the file that ships inside the compiled binary.
// Idempotent: skips the write when bytes are unchanged, so a no-op build leaves the
// working tree clean (the release step's clean-tree precondition stays satisfied).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const SEMVER = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

export function renderVersionModule(version) {
  if (typeof version !== 'string' || !SEMVER.test(version)) {
    throw new Error(`genversion: package.json "version" is not valid semver: ${JSON.stringify(version)}`);
  }
  return `// Generated by scripts/genversion.mjs from package.json — do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`;
}

function main() {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const next = renderVersionModule(pkg.version);
  const target = join(root, 'src', 'version.ts');
  let current = '';
  try { current = readFileSync(target, 'utf8'); } catch { /* first run */ }
  if (current === next) {
    console.log(`genversion: src/version.ts already at ${pkg.version}`);
    return;
  }
  writeFileSync(target, next);
  console.log(`genversion: wrote src/version.ts (${pkg.version})`);
}

// Run only when invoked directly, so importing it in tests has no side effects.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
